apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: embedding-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: embedding-app-deployment
  minReplicas: 2 # Minimum number of replicas
  maxReplicas: 10 # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # Target CPU utilization percentage
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 800Mi # Target average memory utilization
