apiVersion: v1
kind: Service
metadata:
  name: embedding-app-service
spec:
  selector:
    app: embedding-app
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 5000 # Container port
  type: LoadBalancer # Use LoadBalancer for external access
